apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fsteps-front
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: fsteps-front
    spec:
      containers:
        - image: philsabaty/fsteps-front:v0.4
          imagePullPolicy: Always
          name: fsteps-front
          env:
          - name: MYSQL_HOST_1STEPS
            value: "fsteps-db"
#            value: "10.108.164.122"
          ports:
            - containerPort: 80