apiVersion: v1
kind: Pod
metadata:
  name: fsteps-db
  labels:
    app: fsteps-db
spec:
  containers:
    - image: philsabaty/fsteps-db
      name: fsteps-db
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "root"
      - name: MYSQL_DATABASE
        value: "first_steps"
      ports:
      - containerPort: 3306
